/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sarh.forms;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author User1
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deskMain = new javax.swing.JDesktopPane();
        txtCorreoCorp = new javax.swing.JTextField();
        bttLogin = new javax.swing.JButton();
        passwordRecuperar = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        lblLoginH1 = new javax.swing.JLabel();
        ckbMostrarPassword = new javax.swing.JCheckBox();
        logoImage = new javax.swing.JLabel();
        backgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SARH");

        deskMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCorreoCorp.setBackground(new java.awt.Color(51, 51, 51));
        txtCorreoCorp.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        txtCorreoCorp.setForeground(new java.awt.Color(153, 153, 153));
        txtCorreoCorp.setText("Email Corporativo");
        txtCorreoCorp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 5));
        txtCorreoCorp.setPreferredSize(new java.awt.Dimension(64, 22));
        txtCorreoCorp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCorreoCorpFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCorreoCorpFocusLost(evt);
            }
        });
        deskMain.add(txtCorreoCorp, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 180, 150, -1));

        bttLogin.setBackground(new java.awt.Color(51, 51, 51));
        bttLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bttLogin.setForeground(new java.awt.Color(234, 234, 234));
        bttLogin.setText("Ingresar");
        bttLogin.setBorder(null);
        bttLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttLoginActionPerformed(evt);
            }
        });
        deskMain.add(bttLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 116, 30));

        passwordRecuperar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        passwordRecuperar.setForeground(new java.awt.Color(234, 234, 234));
        passwordRecuperar.setText("¿Olvidó su contraseña?");
        passwordRecuperar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deskMain.add(passwordRecuperar, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 320, -1, -1));

        txtPassword.setBackground(new java.awt.Color(51, 51, 51));
        txtPassword.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(153, 153, 153));
        txtPassword.setText("Contraseña");
        txtPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 5));
        txtPassword.setEchoChar('\u0000');
        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasswordFocusLost(evt);
            }
        });
        deskMain.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 220, 150, 22));

        lblLoginH1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblLoginH1.setForeground(new java.awt.Color(234, 234, 234));
        lblLoginH1.setText("Inicio de sesión");
        deskMain.add(lblLoginH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 20, -1, -1));

        ckbMostrarPassword.setForeground(new java.awt.Color(234, 234, 234));
        ckbMostrarPassword.setText("Mostrar Contraseña");
        ckbMostrarPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbMostrarPasswordActionPerformed(evt);
            }
        });
        deskMain.add(ckbMostrarPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 250, -1, -1));

        logoImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LogoCol_120px.png"))); // NOI18N
        deskMain.add(logoImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 120, 120));

        backgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FondoPrincipal.png"))); // NOI18N
        deskMain.add(backgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deskMain, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deskMain)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCorreoCorpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCorreoCorpFocusGained
        if(txtCorreoCorp.getText().equals("Email Corporativo")){
            txtCorreoCorp.setText("");
            txtCorreoCorp.setForeground(new Color(234, 234, 234));
        }        
    }//GEN-LAST:event_txtCorreoCorpFocusGained

    private void txtCorreoCorpFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCorreoCorpFocusLost
        if(txtCorreoCorp.getText().equals("")){
            txtCorreoCorp.setText("Email Corporativo");
            txtCorreoCorp.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtCorreoCorpFocusLost

    private void txtPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusGained
        String password = String.valueOf(txtPassword.getPassword());        
        if(password.equals("Contraseña")){
            txtPassword.setText("");
            txtPassword.setEchoChar('*');            
            txtPassword.setForeground(new Color(234, 234, 234));
        }        
    }//GEN-LAST:event_txtPasswordFocusGained

    private void txtPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusLost
        String password = String.valueOf(txtPassword.getPassword());        
        if(password.equals("")){
            txtPassword.setText("Contraseña");
            txtPassword.setEchoChar((char)0);            
            txtPassword.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtPasswordFocusLost

    private void ckbMostrarPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbMostrarPasswordActionPerformed
        if(String.valueOf(txtPassword.getPassword()).equals("Contraseña"))
            return;
        if(ckbMostrarPassword.isSelected()){
            txtPassword.setEchoChar((char) 0);
        } else{
            txtPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_ckbMostrarPasswordActionPerformed

    private void bttLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttLoginActionPerformed
        
        if(txtCorreoCorp.getText().equals("admin") && String.valueOf(txtPassword.getPassword()).equals("admin")){
            UsuarioAdministrador adminFrame = new UsuarioAdministrador();
            adminFrame.setVisible(true);
            
            dispose();
        }
        if(txtCorreoCorp.getText().equals("user") && String.valueOf(txtPassword.getPassword()).equals("user")){
            UsuarioEstandar userFrame = new UsuarioEstandar();
            userFrame.setVisible(true);
            
            dispose();
        }
    }//GEN-LAST:event_bttLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundImage;
    private javax.swing.JButton bttLogin;
    private javax.swing.JCheckBox ckbMostrarPassword;
    private javax.swing.JDesktopPane deskMain;
    private javax.swing.JLabel lblLoginH1;
    private javax.swing.JLabel logoImage;
    private javax.swing.JLabel passwordRecuperar;
    private javax.swing.JTextField txtCorreoCorp;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
