
package sarh.forms;

import images.TableActionCellEditor;
import images.TableActionCellRenderer;
import images.TableActionEvent;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sql.ConectarPsql;


public class UsuarioAdministrador extends javax.swing.JFrame {

    java.sql.Connection conn=null;
    public UsuarioAdministrador() throws ClassNotFoundException, SQLException {
        initComponents();
        panelNuevoingreso.setVisible(false);
        llenarDatos();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deskUsuarioAdmin = new javax.swing.JDesktopPane();
        scrollLista = new javax.swing.JScrollPane();
        tableEmpleados = new javax.swing.JTable();
        panelLista = new javax.swing.JPanel();
        BotonActualizar = new javax.swing.JButton();
        txtpuesto = new javax.swing.JTextField();
        txtcodigo = new javax.swing.JTextField();
        txtuniorga = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtfechfin = new javax.swing.JTextField();
        txtfechaini = new javax.swing.JTextField();
        panelNuevoingreso = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        menuAdmin = new javax.swing.JMenuBar();
        menuGestionEmpleados = new javax.swing.JMenu();
        itemListaEmpleados = new javax.swing.JMenuItem();
        itemEmpleadosPerformance = new javax.swing.JMenuItem();
        itemReclutamiento = new javax.swing.JMenuItem();
        menuNomina = new javax.swing.JMenu();
        menuSolicitudesLaborales = new javax.swing.JMenu();
        menuInformes = new javax.swing.JMenu();
        opcionLogOff = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {}
            },
            new String [] {

            }
        ));
        tableEmpleados.setGridColor(new java.awt.Color(230, 230, 230));
        tableEmpleados.setRowHeight(40);
        tableEmpleados.setSelectionBackground(new java.awt.Color(57, 137, 111));
        tableEmpleados.getTableHeader().setReorderingAllowed(false);
        tableEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableEmpleadosMouseClicked(evt);
            }
        });
        scrollLista.setViewportView(tableEmpleados);
        if (tableEmpleados.getColumnModel().getColumnCount() > 0) {
            tableEmpleados.getColumnModel().getColumn(0).setResizable(false);
            tableEmpleados.getColumnModel().getColumn(1).setResizable(false);
            tableEmpleados.getColumnModel().getColumn(2).setResizable(false);
            tableEmpleados.getColumnModel().getColumn(3).setResizable(false);
            tableEmpleados.getColumnModel().getColumn(4).setResizable(false);
            tableEmpleados.getColumnModel().getColumn(5).setResizable(false);
        }

        BotonActualizar.setText("Actualizar Datos");
        BotonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonActualizarActionPerformed(evt);
            }
        });

        txtpuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpuestoActionPerformed(evt);
            }
        });

        txtcodigo.setEnabled(false);

        txtuniorga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuniorgaActionPerformed(evt);
            }
        });

        jLabel1.setText("Codigo Usuario");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel2.setText("Actualizar Datos de los Usuarios");

        jLabel3.setText("Puesto");

        jLabel4.setText("Unidad Organizativa");

        jLabel5.setText("Fecha Fin");

        jLabel6.setText("Fecha Inicio");

        txtfechaini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfechainiActionPerformed(evt);
            }
        });

        jTextField1.setText("jTextField1");

        jTextField2.setText("jTextField2");

        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelNuevoingresoLayout = new javax.swing.GroupLayout(panelNuevoingreso);
        panelNuevoingreso.setLayout(panelNuevoingresoLayout);
        panelNuevoingresoLayout.setHorizontalGroup(
            panelNuevoingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNuevoingresoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        panelNuevoingresoLayout.setVerticalGroup(
            panelNuevoingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNuevoingresoLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(panelNuevoingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelListaLayout = new javax.swing.GroupLayout(panelLista);
        panelLista.setLayout(panelListaLayout);
        panelListaLayout.setHorizontalGroup(
            panelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListaLayout.createSequentialGroup()
                .addGroup(panelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelListaLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(BotonActualizar))
                    .addGroup(panelListaLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(panelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(panelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(panelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtuniorga, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(panelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtfechaini, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfechfin, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelListaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 215, Short.MAX_VALUE)
                .addComponent(panelNuevoingreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        panelListaLayout.setVerticalGroup(
            panelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListaLayout.createSequentialGroup()
                .addGroup(panelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelListaLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelNuevoingreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addGap(31, 31, 31)
                .addGroup(panelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtuniorga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtfechaini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtfechfin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(BotonActualizar)
                .addContainerGap(761, Short.MAX_VALUE))
        );

        jButton1.setText("Insertar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        deskUsuarioAdmin.setLayer(scrollLista, javax.swing.JLayeredPane.DEFAULT_LAYER);
        deskUsuarioAdmin.setLayer(panelLista, javax.swing.JLayeredPane.DEFAULT_LAYER);
        deskUsuarioAdmin.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout deskUsuarioAdminLayout = new javax.swing.GroupLayout(deskUsuarioAdmin);
        deskUsuarioAdmin.setLayout(deskUsuarioAdminLayout);
        deskUsuarioAdminLayout.setHorizontalGroup(
            deskUsuarioAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deskUsuarioAdminLayout.createSequentialGroup()
                .addGroup(deskUsuarioAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deskUsuarioAdminLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(deskUsuarioAdminLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jButton1)))
                .addContainerGap())
            .addComponent(scrollLista)
        );
        deskUsuarioAdminLayout.setVerticalGroup(
            deskUsuarioAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deskUsuarioAdminLayout.createSequentialGroup()
                .addComponent(scrollLista, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuGestionEmpleados.setText("Gestión de Empleados");

        itemListaEmpleados.setText("Lista de Empleados");
        itemListaEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemListaEmpleadosActionPerformed(evt);
            }
        });
        menuGestionEmpleados.add(itemListaEmpleados);

        itemEmpleadosPerformance.setText("Desempeño de Empleados");
        menuGestionEmpleados.add(itemEmpleadosPerformance);

        itemReclutamiento.setText("Reclutamiento y Selección");
        menuGestionEmpleados.add(itemReclutamiento);

        menuAdmin.add(menuGestionEmpleados);

        menuNomina.setText("Administrar Nómina");
        menuAdmin.add(menuNomina);

        menuSolicitudesLaborales.setText("Solicitudes Laborales");
        menuAdmin.add(menuSolicitudesLaborales);

        menuInformes.setText("Gestión de Informes");
        menuAdmin.add(menuInformes);

        opcionLogOff.setText("Cerrar Sesión");
        opcionLogOff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                opcionLogOffMouseClicked(evt);
            }
        });
        menuAdmin.add(opcionLogOff);

        setJMenuBar(menuAdmin);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deskUsuarioAdmin)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deskUsuarioAdmin)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemListaEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemListaEmpleadosActionPerformed
        
    }//GEN-LAST:event_itemListaEmpleadosActionPerformed

    private void opcionLogOffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opcionLogOffMouseClicked
        int resp = JOptionPane.showConfirmDialog(null, "¿Está seguro de cerrar su sesión?",
                                                "Cerrar Sesión", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);        
        if(resp == 0 || resp ==-1){
            
            Principal login = new Principal();
            this.dispose();            
            login.setVisible(true);
        }
    }//GEN-LAST:event_opcionLogOffMouseClicked

    private void BotonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonActualizarActionPerformed
        try {
            // TODO add your handling code here:
            guardar();
        } catch (SQLException ex) {
            Logger.getLogger(UsuarioAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BotonActualizarActionPerformed

    private void tableEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableEmpleadosMouseClicked
        int selec=tableEmpleados.rowAtPoint(evt.getPoint());
        txtcodigo.setText(String.valueOf(tableEmpleados.getValueAt( selec,0)));
        txtpuesto.setText(String.valueOf(tableEmpleados.getValueAt( selec,2)));
        txtuniorga.setText(String.valueOf(tableEmpleados.getValueAt( selec,3)));
        txtfechaini.setText(String.valueOf(tableEmpleados.getValueAt( selec,4)));
        txtfechfin.setText(String.valueOf(tableEmpleados.getValueAt( selec,5)));
    }//GEN-LAST:event_tableEmpleadosMouseClicked

    private void txtpuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpuestoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        panelLista.setVisible(false);
        panelNuevoingreso.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            guardar_datos();
        } catch (SQLException ex) {
            Logger.getLogger(UsuarioAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }
        panelNuevoingreso.setVisible(false);  
       

 panelLista.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         panelLista.setVisible(true);
        panelNuevoingreso.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtuniorgaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuniorgaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuniorgaActionPerformed

    private void txtfechainiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfechainiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfechainiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsuarioAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsuarioAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsuarioAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsuarioAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new UsuarioAdministrador().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(UsuarioAdministrador.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(UsuarioAdministrador.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
      public void llenarDatos() throws ClassNotFoundException, SQLException{
        
         Class.forName("org.postgresql.Driver");
        String V_pass=null;
        String rpt=null;
        String url = "jdbc:postgresql://localhost:5432/SARH";
        String cadena="select Codempleado,nombre,puesto,uorgani,fechainicontrato,fechafincontra from empleado ";
       
        conn = DriverManager.getConnection(url, "postgres", "sa");
        
        PreparedStatement stmt = null;
        
        stmt = conn.prepareStatement(cadena);
        
        ResultSet rs = stmt.executeQuery();
          DefaultTableModel modelo = new DefaultTableModel();

 
     int i;
 
 
 
     modelo.addColumn("Codempleado");
     modelo.addColumn("Nombre");
     modelo.addColumn("Puesto");
     modelo.addColumn("Unidad Organizativa");
     modelo.addColumn("Fecha Inicio");
     modelo.addColumn("Fecha Fin");
     
      String  fila[] = new String[6];
      String var =null;
     while (rs.next())
 {
    // Se crea un array que será una de las filas de la tabla. 
 
 
    // Se rellena cada posición del array con una de las columnas de la tabla en base de datos.
    //for ( i=0;i<3;i++){
        fila[0] = rs.getString("Codempleado"); // El primer indice en rs es el 1, no el cero, por eso se suma 1.
        fila[1] = rs.getString("nombre");
        fila[2] = rs.getString("puesto");
        fila[3] = rs.getString("uorgani");
        fila[4] = rs.getString("fechainicontrato");
        fila[5] = rs.getString("fechafincontra");
 
   // }
    // Se añade al modelo la fila completa.
    modelo.addRow(fila);
           }
     tableEmpleados.setModel(modelo);
     
}
    public void guardar() throws SQLException{
        try{
        Class.forName("org.postgresql.Driver");
        String V_pass=null;
        String v_perfil=null;
        String rpt=null;
        String fecini=null;
        String fecfin=null;
        PreparedStatement stmt = null;
        String url = "jdbc:postgresql://localhost:5432/SARH";
        //String cadena="insert into empleado(codempleado) values(?)";
        fecini=txtfechfin.getText();
        if (fecini.length() == 0){
              fecini="fechainicontrato";
        }else{
        fecini="'" + txtfechaini.getText()+"'";
        }
        fecfin=txtfechfin.getText();
        if (fecfin.length() == 0){
              fecfin="fechafincontra";
        }else{
        fecfin="'" + txtfechfin.getText()+"'";
        }
        String cadena="update empleado set puesto='"+txtpuesto.getText()+"',uorgani='"+ txtuniorga.getText()+"',fechainicontrato="+fecini+",fechafincontra="+fecfin+" where codempleado='"+ txtcodigo.getText()+"'";
        txtuniorga.setText(cadena);
        conn = DriverManager.getConnection(url, "postgres", "sa");

        stmt = conn.prepareStatement(cadena);

        stmt.executeUpdate();
        limpiar();
     
        tableEmpleados.setModel(new DefaultTableModel());
        llenarDatos();
        
        }catch (ClassNotFoundException ex) {
            Logger.getLogger(ConectarPsql.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void guardar_datos() throws SQLException{
        try{
        Class.forName("org.postgresql.Driver");
        String V_pass=null;
        String v_perfil=null;
        String rpt=null;
        String fec=null;
        PreparedStatement stmt = null;
        String url = "jdbc:postgresql://localhost:5432/SARH";
        String cadena="insert into empleado(codempleado,puesto) values(?,?)";
        
        conn = DriverManager.getConnection(url, "postgres", "sa");

        stmt = conn.prepareStatement(cadena);
        stmt.setString(1, jTextField1.getText());
        stmt.setString(2, jTextField2.getText());
            //stmt.setString(3, modelo.getSexo());
        stmt.executeUpdate();
        limpiar_insertar();
     
        tableEmpleados.setModel(new DefaultTableModel());
        llenarDatos();
        
        
        }catch (ClassNotFoundException ex) {
            Logger.getLogger(ConectarPsql.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
     public void limpiar() {
     txtpuesto.setText(null);
     txtfechaini.setText(null);
     txtcodigo.setText(null);
     txtfechfin.setText(null);
     }
     public void limpiar_insertar() {
     jTextField1.setText(null);
     jTextField2.setText(null);
     }
    
    
   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonActualizar;
    private javax.swing.JDesktopPane deskUsuarioAdmin;
    private javax.swing.JMenuItem itemEmpleadosPerformance;
    private javax.swing.JMenuItem itemListaEmpleados;
    private javax.swing.JMenuItem itemReclutamiento;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JMenuBar menuAdmin;
    private javax.swing.JMenu menuGestionEmpleados;
    private javax.swing.JMenu menuInformes;
    private javax.swing.JMenu menuNomina;
    private javax.swing.JMenu menuSolicitudesLaborales;
    private javax.swing.JMenu opcionLogOff;
    private javax.swing.JPanel panelLista;
    private javax.swing.JPanel panelNuevoingreso;
    private javax.swing.JScrollPane scrollLista;
    private javax.swing.JTable tableEmpleados;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtfechaini;
    private javax.swing.JTextField txtfechfin;
    private javax.swing.JTextField txtpuesto;
    private javax.swing.JTextField txtuniorga;
    // End of variables declaration//GEN-END:variables
}
